* ebtrfs/efs
Using encryption over btrfs (or any filesystem without snapshot feature)

** Selected scheme
This solution uses ecryptfs filesystem over btrfs subvolume:
  - <volname>: ecryptfs mount path
  - .<volname>.ecryptfs: btrfs subvolume (or simple dir)
  - .<volname>.ecryptfs/root: ecryptfs root
  - .<volname>.ecryptfs/sig: key signature
  - /etc/fstab: used to mount home encrypted volumes

** Install
#+BEGIN_SRC sh
wget -q -O ecryptbtrfs_installer.sh https://raw.githubusercontent.com/oszika/ecryptbtrfs/master/installer.sh && chmod u+x ecryptbtrfs_installer.sh && sudo ./ecryptbtrfs_installer.sh; rm ecryptbtrfs_installer.sh
#+END_SRC

** Scripts
  - ebtrfs: ecryptfs over btrfs
  - efs: ecryptfs over any filesystem
With ebtrfs, subvolumes are encrypted. Otherwise, a simple dir is used.

** Create encrypted volume
#+BEGIN_SRC sh
$ ebtrfs create /volumes/voltest
#+END_SRC

#+BEGIN_SRC sh
Create subvolume '/volumes/.voltest.ecryptfs'
[debug]	 Subvolume /volumes/.voltest.ecryptfs created
[debug]	 Mount dir /volumes/voltest created
[debug]	 Ecryptfs root /volumes/.voltest.ecryptfs/root created
Passphrase:
Passphrase: (verify)
[debug]	 Ecryptfs configuration written
[debug]	 User rights setted (user)
#+END_SRC

** Mount/Umount encrypted volume
#+BEGIN_SRC sh
$ ebtrfs mount /volumes/voltest
$ ebtrfs umount /volumes/voltest
#+END_SRC

** Check encrypted volume
#+BEGIN_SRC sh
$ echo pouet > /volumes/voltest/pouet

$ ls /volumes/voltest/
/volumes/voltest/pouet

$ ls /volumes/.voltest.ecryptfs/root
ECRYPTFS_FNEK_ENCRYPTED.FWaEAm4HEfHTMUQRparKutvJjA2s-IhrvvEwRlFqpRonsgrxKUmz3XSAf---
#+END_SRC

** List encrypted volumes
#+BEGIN_SRC sh
$ sudo ebtrfs list /
#+END_SRC

#+BEGIN_SRC sh
ID 312 gen 4533 parent 5 top level 5 path volumes/voltest
#+END_SRC

** Take snapshot
First snapshot is named as 'init'. The others are generated with dates.

#+BEGIN_SRC sh
$ ebtrfs snapshot -r /volumes/voltest
#+END_SRC

#+BEGIN_SRC sh
Create a readonly snapshot of '/volume/.voltest.ecryptfs' in '/volumes/.voltest.snaps/.init.ecryptfs'
#+END_SRC

#+BEGIN_SRC sh
$ ebtrfs snapshot -r /volumes/voltest
#+END_SRC

#+BEGIN_SRC sh
Create a readonly snapshot of '/volume/.voltest.ecryptfs' in '/volumes/.voltest.snaps/.2017-06-10-16:05:06.ecryptfs'
#+END_SRC

** Create home encrypted volume
*** You need to create encrypted volume using sudo to write on /home.
#+BEGIN_SRC sh
$ sudo ebtrfs create /home/toto
#+END_SRC
*** Reset owner
#+BEGIN_SRC sh
$ sudo chown -R toto /home/.toto
$ sudo chown -R toto /home/toto
#+END_SRC
*** Setting volume to be auto mounted at login
#+BEGIN_SRC sh
$ ebtrfs home /home/toto
#+END_SRC

#+BEGIN_SRC sh
[info]	 Wrapping ecryptfs password
Passphrase to wrap:
Wrapping passphrase:
Setting user pam conf
[debug]	 Fstab updated
#+END_SRC
